# Generated by Django 3.1 on 2024-03-21 17:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servername', models.CharField(max_length=100)),
                ('wellid', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created_at_ms', models.BigIntegerField(blank=True, null=True)),
                ('trained_at_ms', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('backtest_start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('progress', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algo_name', models.CharField(blank=True, max_length=100, null=True)),
                ('servername', models.CharField(blank=True, max_length=100, null=True)),
                ('wellid', models.CharField(blank=True, max_length=100, null=True)),
                ('start', models.BigIntegerField(blank=True, null=True)),
                ('end', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at_ms', models.BigIntegerField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('model_description', models.CharField(blank=True, max_length=300, null=True)),
                ('mse', models.FloatField(blank=True, null=True)),
                ('trained_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('model_type', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_source', models.CharField(blank=True, max_length=100, null=True)),
                ('inputs', models.TextField(blank=True, null=True)),
                ('is_generic', models.BooleanField(blank=True, null=True)),
                ('last_trained', models.DateTimeField(blank=True, null=True)),
                ('training_time', models.BigIntegerField(blank=True, null=True)),
                ('execution_time', models.BigIntegerField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servername', models.CharField(max_length=100)),
                ('wellid', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at_ms', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algo_name', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start', models.BigIntegerField(blank=True, null=True)),
                ('end', models.BigIntegerField(blank=True, null=True)),
                ('model_description', models.CharField(blank=True, max_length=300, null=True)),
                ('is_generic', models.BooleanField(blank=True, null=True)),
                ('inputs', models.TextField(blank=True, null=True)),
                ('mse', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_at_ms', models.BigIntegerField(blank=True, null=True)),
                ('model_type', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_source', models.CharField(blank=True, max_length=100, null=True)),
                ('last_trained', models.DateTimeField(blank=True, null=True)),
                ('training_time', models.BigIntegerField(blank=True, null=True)),
                ('execution_time', models.BigIntegerField(blank=True, null=True)),
                ('training_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='corepredict.trainingstatus')),
            ],
        ),
    ]
