# Generated by Django 3.1 on 2024-06-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corepredict', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainedmodel',
            name='algo_name',
        ),
    ]
