# Generated by Django 3.1 on 2024-07-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corepredict', '0002_remove_trainedmodel_algo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainedmodel',
            name='model_type',
        ),
        migrations.RemoveField(
            model_name='trainingmetrics',
            name='model_type',
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='performance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='performance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='target_column',
            field=models.TextField(blank=True, null=True),
        ),
    ]
