# Generated by Django 3.1 on 2024-07-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corepredict', '0003_auto_20240715_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='y_scaler_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='y_scaler_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
