# Generated by Django 3.1 on 2024-07-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corepredict', '0004_auto_20240718_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmetrics',
            name='algo_name',
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='target_column',
            field=models.TextField(blank=True, null=True),
        ),
    ]
