# Generated by Django 3.2.3 on 2022-07-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='training_id',
        ),
        migrations.AlterField(
            model_name='training',
            name='training_status',
            field=models.BooleanField(),
        ),
    ]
