# Generated by Django 3.2.3 on 2022-07-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220727_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_status',
            field=models.BooleanField(blank=True),
        ),
    ]
