# Generated by Django 3.2.3 on 2022-08-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_training_training_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='trained_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
