# Generated by Django 3.2.3 on 2022-08-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_training_trained_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_status',
            field=models.CharField(choices=[('start_training', 'TRAINING'), ('end_of_training', 'FINISH')], max_length=19),
        ),
    ]
