# Generated by Django 3.2.3 on 2022-08-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_training_training_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_status',
            field=models.CharField(choices=[('training', 'training'), ('complete', 'complete')], max_length=19),
        ),
    ]
