# Generated by Django 3.2.3 on 2022-11-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_training_training_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='servername',
            field=models.CharField(default='stage', max_length=20),
        ),
    ]
