# Generated by Django 3.2.3 on 2023-01-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_training_servername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='deep',
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='accuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='loss',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='servername',
            field=models.CharField(default='stage', max_length=30),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='model_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
