# Generated by Django 3.2.3 on 2023-01-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230118_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='well_id',
            new_name='wellid',
        ),
    ]
