# Generated by Django 3.0 on 2023-01-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_well_id_training_wellid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servername', models.CharField(default='stage', max_length=20)),
                ('wellid', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('complete', 'Complete')], max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Training',
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
