# Generated by Django 3.0 on 2023-02-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230131_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.BinaryField(blank=True, null=True)),
                ('servername', models.CharField(default='stage', max_length=30)),
                ('model_name', models.CharField(blank=True, max_length=30, null=True)),
                ('accuracy', models.FloatField(null=True)),
                ('loss', models.FloatField(null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
