# Generated by Django 3.1 on 2023-02-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_trainedmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('training_loss', models.FloatField()),
                ('training_accuracy', models.FloatField()),
                ('validation_loss', models.FloatField()),
                ('validation_accuracy', models.FloatField()),
                ('training_losses', models.JSONField()),
                ('validation_losses', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
