# Generated by Django 3.1 on 2023-02-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_evaluationmetrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainedmodel',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='loss',
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='model',
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='model_data',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='wellid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='model_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='servername',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
