# Generated by Django 3.1 on 2023-02-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230222_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wellid', models.IntegerField()),
                ('servername', models.CharField(max_length=100)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('tags', models.CharField(max_length=100)),
                ('samples', models.IntegerField()),
                ('noise', models.FloatField()),
                ('days', models.IntegerField()),
                ('batch_size', models.IntegerField()),
                ('latent_dim', models.IntegerField()),
                ('intermediate_dim1', models.IntegerField()),
                ('intermediate_dim2', models.IntegerField()),
                ('epochs', models.IntegerField()),
                ('epsilon_std', models.FloatField()),
                ('model_name', models.CharField(max_length=100)),
                ('model_description', models.TextField()),
                ('training_loss', models.FloatField()),
                ('training_accuracy', models.FloatField()),
                ('validation_loss', models.FloatField()),
                ('validation_accuracy', models.FloatField()),
                ('training_loss_values', models.JSONField()),
                ('training_accuracy_values', models.JSONField()),
                ('validation_loss_values', models.JSONField()),
                ('validation_accuracy_values', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
