# Generated by Django 3.1 on 2023-02-25 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_trainingresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingresult',
            name='batch_size',
        ),
        migrations.RemoveField(
            model_name='trainingresult',
            name='days',
        ),
        migrations.RemoveField(
            model_name='trainingresult',
            name='end',
        ),
        migrations.RemoveField(
            model_name='trainingresult',
            name='epochs',
        ),
        migrations.RemoveField(
            model_name='trainingresult',
            name='epsilon_std',
        ),
        migrations.RemoveField(
            model_name='trainingresult',
            name='intermediate_dim1',
        ),
        migrations.RemoveField(
            model_name='trainingresult',
            name='intermediate_dim2',
        ),
        migrations.RemoveField(
            model_name='trainingresult',
            name='latent_dim',
        ),
        migrations.RemoveField(
            model_name='trainingresult',
            name='noise',
        ),
        migrations.RemoveField(
            model_name='trainingresult',
            name='samples',
        ),
        migrations.RemoveField(
            model_name='trainingresult',
            name='start',
        ),
        migrations.RemoveField(
            model_name='trainingresult',
            name='tags',
        ),
    ]
