# Generated by Django 3.1 on 2023-02-25 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20230225_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingstatus',
            old_name='end_time',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='trainingstatus',
            old_name='start_time',
            new_name='started_at',
        ),
        migrations.RemoveField(
            model_name='trainingstatus',
            name='status',
        ),
        migrations.AlterField(
            model_name='trainingstatus',
            name='servername',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trainingstatus',
            name='wellid',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='TrainingMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_loss', models.FloatField(blank=True, null=True)),
                ('training_accuracy', models.FloatField(blank=True, null=True)),
                ('validation_loss', models.FloatField(blank=True, null=True)),
                ('validation_accuracy', models.FloatField(blank=True, null=True)),
                ('training_loss_values', models.TextField(blank=True, null=True)),
                ('training_accuracy_values', models.TextField(blank=True, null=True)),
                ('validation_loss_values', models.TextField(blank=True, null=True)),
                ('validation_accuracy_values', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.trainingstatus')),
            ],
        ),
    ]
