# Generated by Django 3.1 on 2023-02-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20230225_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingstatus',
            name='status',
            field=models.CharField(default='in progress', max_length=20),
        ),
    ]
