# Generated by Django 3.1 on 2023-02-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20230226_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingstatus',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
