# Generated by Django 3.1 on 2023-02-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20230226_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingstatus',
            name='model_description',
        ),
        migrations.RemoveField(
            model_name='trainingstatus',
            name='model_name',
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='model_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
