# Generated by Django 3.1 on 2023-04-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_trainingmetrics_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmetrics',
            name='user_id',
        ),
    ]
