# Generated by Django 3.1 on 2023-04-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_trainingmetrics_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='execution_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='inputs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='is_generic',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='last_trained',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='training_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='execution_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='inputs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='is_generic',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='last_trained',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='training_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
