# Generated by Django 3.1 on 2023-04-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20230413_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
