# Generated by Django 3.1 on 2023-05-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_trainedmodel_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
