# Generated by Django 3.1 on 2023-06-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20230502_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='algo_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='algo_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
