# Generated by Django 3.1 on 2023-08-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20230720_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='created_at_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='created_at_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingstatus',
            name='created_at_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
