# Generated by Django 3.1 on 2023-08-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20230822_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servername', models.CharField(max_length=100)),
                ('wellid', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created_at_ms', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
