# Generated by Django 3.1 on 2023-08-25 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_testingstatus_trained_at_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingstatus',
            name='backtest_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
