# Generated by Django 3.1 on 2023-11-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_testingstatus_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmetrics',
            name='end',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='start',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
