# Generated by Django 3.1 on 2023-11-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20231122_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='end',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='start',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
