# Generated by Django 3.1 on 2024-06-25 11:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20231122_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmetrics',
            name='end',
        ),
        migrations.RemoveField(
            model_name='trainingmetrics',
            name='scaler_data',
        ),
        migrations.RemoveField(
            model_name='trainingmetrics',
            name='start',
        ),
        migrations.RemoveField(
            model_name='trainingmetrics',
            name='threshold',
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='pattern_ranges',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
