# Generated by Django 3.1 on 2024-06-25 11:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20240625_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainedmodel',
            name='end',
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='scaler_data',
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='start',
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='threshold',
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='pattern_ranges',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
