# Generated by Django 3.1 on 2024-07-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20240625_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedmodel',
            name='pattern_ranges',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingmetrics',
            name='pattern_ranges',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
